
services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mongo
    restart: unless-stopped




  config-server-ms:
    image: parthdocker17/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 5004:5004
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - mongo
    environment:
      - SPRING_PROFILE_ACTIVE=docker

  servicereg:
    image: parthdocker17/servicereg:latest
    container_name: servicereg
    ports:
      - "8070:8070"
    depends_on:
      - zipkin
      - mongo
      - mongo-express
    networks:
      - microservice-network
      - mongo

  taskms:
    image: parthdocker17/taskms:latest
    container_name: task
    ports:
      - 5002:5002
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - mongo
    environment:
      - SPRING_PROFILE_ACTIVE=docker


  submissionms:
    image: parthdocker17/submissionms:latest
    container_name: submission
    ports:
      - 5003:5003
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - mongo
    environment:
      - SPRING_PROFILE_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://servicereg:8070/eureka


  userms:
    image: parthdocker17/userms:latest
    container_name: user
    ports:
      - 5001:5001
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - mongo
    environment:
      - SPRING_PROFILE_ACTIVE=docker


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

    networks:
      - microservice-network
      - mongo



  gateway-ms:
    image: parthdocker17/gateway-ms:latest
    container_name: gateway
    ports:
      - 5000:5000
    depends_on:
      - servicereg

    networks:
      - microservice-network
      - mongo
    environment:
      - SPRING_PROFILE_ACTIVE=docker

networks:
  microservice-network:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  mongo:
  mongo_express:







