server:
  port: 5000


spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes :

        - id: user_service
          uri:
              http://user:5001
          predicates:
              - Path=/auth/**, /users/**, /api/users/**, /

        - id: task_service
          uri:
              http://task:5002
          predicates:
              - Path=/tasks/**, /api/tasks/**

        - id: task_submission_service
          uri:
              http://submission:5003
          predicates:
               - Path=/submissions/**, /api/submissions/**

              # for Eureka Server

        - id: eurekaserver
          uri:
                  http://servicereg:8070
          predicates:
                  - Path=/eureka/main
          filters:
                - SetPath=/

              # for showing css and js in eureka server as it run by gateway..

        - id: Eureka-Server-static
          uri:
              http://servicereg:8070
          predicates:
                  - Path=/eureka/**




      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders  : "*"




eureka:
  client:
    service-url:
      defaultZone: http://servicereg:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true


management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans




