server:
  port: 5000


spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes :

        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /users/**, /api/users/**, /

        - id: TASK-SERVICE
          uri:
            lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**, /api/tasks/**

        - id: TASK-SUBMISSION-SERVICE
          uri:
            lb://TASK-SUBMISSION-SERVICE
          predicates:
            - Path=/submissions/**, /api/submissions/**

# for Eureka Server

        - id: Eureka-Server
          uri:
            http://localhost:8070
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

# for showing css and js in eureka server as it run by gateway..

        - id: Eureka-Server-static
          uri:
            http://localhost:8070
          predicates:
            - Path=/eureka/**




      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders  : "*"




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true



