task_submission_service:
  url: http://submission:5003

task_service:
  url: http://task:5002

user_service:
  url:  http://user:5001


server:
  port: 5002

spring:
  application:
    name: TASK-SERVICE


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver

#we have to changed to mongodb

    username: root
    password: 1111
    url: jdbc:mysql://MySQL:3306/UserService




eureka:
  client:
    service-url:
      defaultZone: http://serviceregistry:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true


management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans



