server:
  port: 5004

spring:
  application:
    name: config-server


# config server


  cloud:
    config:
      server:
        git:
          uri: https://github.com/ParthModi293/Application-Config-ProjectManagementMicroservice/



# Eureka client

eureka:
  client:
    service-url:
      defaultZone: http://servicereg:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

